version: "3.9"
services:
  mongo:
    image: mongo:4.0.10
    ports:
      - "27017:27017"
  app:
    depends_on:
      - mongo
    image: app-mongo-1
    build: "."
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/test"