GET http://localhost:8080/
###
GET http://localhost:8080/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTY2MTgwOTc3NSwiaWF0IjoxNjYxNzczNzc1LCJzY29wZSI6ImFwcCJ9.rcdCDYbbAeQXnU1-XRGpCQOcZYZI5hArHSCsxY6Rdbf_mRQmIUbiXOw4kIfz8rWKOhwwRVUtxm0NTGEmYt0urhBJCaeGmdCFyj7RxqpzBl-QxqrS-1Dbrg-j7a_Y_gFJ_W04lYt4j3DhYqGLdFUJUBJKaUo14RAGCcOX1DmPe9CwfYZ8WTv4bdGqiFD_S8XmHiao751ZMyTEraWpvw34cRXDaFwCoq0q6friFh-GHBujUZpH5EHVBIGF2CZq3XX0m57wc7k7xpq2qWJVzRWi_O8XjQzjYbwpQvh0xYn-cAbCWLCe8NzsNtxJFZaLlGaAoZ4LGcR0dITCOvlHqOtYWA
###
GET http://localhost:8080/user
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTY2MTg5MjkxMywiaWF0IjoxNjYxODU2OTEzLCJzY29wZSI6ImFwcCJ9.V3CErqug6GWhOXR3LH9o6B5adxqydrgGx7dNp7rDBaOWkVSMQiCEbZeAbDKL8-FtGfFO4aHY4GdBblDzO_lBn-ihBolPBlzALR_2ytAhqXEDo0VG5Y2olj1F3IIVNHyRrjtCRge2g_6B4wYYTIQQwO4vlPzBnROnjk3Bj2V2ZoxbW2-4OhJFDnseHbLUv2DUX9X5ZI4GWq64m_ffoJnz-jzQhDZmbPD1ySN8KSHaxp5iOKizeXkL-fIP_Qa2VCWH5aTBZzz56E-_g-4saOgff1a1OubGJMxk6mUqDozAHQK92CLh29WWJqLdP095cM_XGk7uBEghXcq-gbE59dYfPQ
###
GET http://localhost:8080/auth
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTY2MTg5MjkxMywiaWF0IjoxNjYxODU2OTEzLCJzY29wZSI6ImFwcCJ9.V3CErqug6GWhOXR3LH9o6B5adxqydrgGx7dNp7rDBaOWkVSMQiCEbZeAbDKL8-FtGfFO4aHY4GdBblDzO_lBn-ihBolPBlzALR_2ytAhqXEDo0VG5Y2olj1F3IIVNHyRrjtCRge2g_6B4wYYTIQQwO4vlPzBnROnjk3Bj2V2ZoxbW2-4OhJFDnseHbLUv2DUX9X5ZI4GWq64m_ffoJnz-jzQhDZmbPD1ySN8KSHaxp5iOKizeXkL-fIP_Qa2VCWH5aTBZzz56E-_g-4saOgff1a1OubGJMxk6mUqDozAHQK92CLh29WWJqLdP095cM_XGk7uBEghXcq-gbE59dYfPQ
###
POST http://localhost:8080/token
Authorization: Basic dXNlcjpwYXNzd29yZA==