GET http://localhost:8080/
###
GET http://localhost:8080/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTY2NDM4Mzg0NiwiaWF0IjoxNjY0MzQ3ODQ2LCJzY29wZSI6ImFwcCJ9.Ojw0iqOjULJ-4XNttYG6pNDrdm8X2KX85-6YRM3ZrIiVvyjFSermTXW9AvP7Bzuvcy1J3IGkQaH4hISAiqgZY-NhNox8_gbnuxdgQAtREz73FbtLdPiwDsOS3zvzRY7Fhcbak-VKdYGfGRe3F72jlZI_hyNbcf-b75W4CVVPT1fJ_dIGwczkmRE6Qw_-MknUpHo8ukitU0cIpbseP5N1LfV9CngSAjooZo8mLpAj4UPnTRncLYR5Xu5O2E73tPlVaMq2ZC8uRZIg0Zj7AxqoJai81j3lWoXJiCb3Epu61Do_Y1bd13XEVGJDZTYa87HLT3SS4lYJ4-Zp4hZGDKpZow
###
GET http://localhost:8080/user
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTY2NDM4Mzg0NiwiaWF0IjoxNjY0MzQ3ODQ2LCJzY29wZSI6ImFwcCJ9.Ojw0iqOjULJ-4XNttYG6pNDrdm8X2KX85-6YRM3ZrIiVvyjFSermTXW9AvP7Bzuvcy1J3IGkQaH4hISAiqgZY-NhNox8_gbnuxdgQAtREz73FbtLdPiwDsOS3zvzRY7Fhcbak-VKdYGfGRe3F72jlZI_hyNbcf-b75W4CVVPT1fJ_dIGwczkmRE6Qw_-MknUpHo8ukitU0cIpbseP5N1LfV9CngSAjooZo8mLpAj4UPnTRncLYR5Xu5O2E73tPlVaMq2ZC8uRZIg0Zj7AxqoJai81j3lWoXJiCb3Epu61Do_Y1bd13XEVGJDZTYa87HLT3SS4lYJ4-Zp4hZGDKpZow
###
GET http://localhost:8080/auth
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTY2NDM4Mzg0NiwiaWF0IjoxNjY0MzQ3ODQ2LCJzY29wZSI6ImFwcCJ9.Ojw0iqOjULJ-4XNttYG6pNDrdm8X2KX85-6YRM3ZrIiVvyjFSermTXW9AvP7Bzuvcy1J3IGkQaH4hISAiqgZY-NhNox8_gbnuxdgQAtREz73FbtLdPiwDsOS3zvzRY7Fhcbak-VKdYGfGRe3F72jlZI_hyNbcf-b75W4CVVPT1fJ_dIGwczkmRE6Qw_-MknUpHo8ukitU0cIpbseP5N1LfV9CngSAjooZo8mLpAj4UPnTRncLYR5Xu5O2E73tPlVaMq2ZC8uRZIg0Zj7AxqoJai81j3lWoXJiCb3Epu61Do_Y1bd13XEVGJDZTYa87HLT3SS4lYJ4-Zp4hZGDKpZow
###
POST http://localhost:8080/token
Authorization: Basic dXNlcjpwYXNzd29yZA==