//json returned
GET http://localhost:8080/json
###
//path variable example
GET http://localhost:8080/json/2
### only in browser
GET http://localhost:8080/json/cacheControl
###
GET http://localhost:8080/json/etag
###
GET http://localhost:8080/json/etagAndCacheControl
###
//view returned
GET http://localhost:8080/view/string
###
GET http://localhost:8080/view/model-and-view
###
//request params example
GET http://localhost:8080/mixed?from=2&to=10
###
GET http://localhost:8080/mixed?from=2
###
GET http://localhost:8080/mixed
//FILTER
### Filter Block
GET http://localhost:8080/json
Block: true